### ISSUE TITLE
Got error using my own data

### ISSUE THREAD

**Issue by ComputerMystery** [carpedm20/DCGAN-tensorflow#102]
Traceback (most recent call last):
  File "/home/sal/Downloads/pycharm-community-2016.2.3/helpers/pydev/pydevd.py", line 1580, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/sal/Downloads/pycharm-community-2016.2.3/helpers/pydev/pydevd.py", line 964, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/sal/PycharmProjects/ReID/GANReID/main.py", line 96, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/sal/PycharmProjects/ReID/GANReID/main.py", line 76, in main
    sample_dir=FLAGS.sample_dir)
  File "/home/sal/PycharmProjects/ReID/GANReID/model.py", line 75, in __init__
    self.build_model()
  File "/home/sal/PycharmProjects/ReID/GANReID/model.py", line 107, in build_model
    self.G = self.generator(self.z)
  File "/home/sal/PycharmProjects/ReID/GANReID/model.py", line 359, in generator
    self.z_, [-1, s_h16, s_w16, self.gf_dim * 8])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 1991, in reshape
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 573, in apply_op
    _Attr(op_def, input_arg.type_attr))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: DataType float32 for attr 'Tshape' not in list of allowed values: int32, int64

**Comment by ComputerMystery** [comment]
Any help will be appreciated

**Comment by ComputerMystery** [comment]
in the model.py seems exits a bug that this part below returns a float for reshape but reshape just accept int32. Need to convert

`def conv_out_size_same(size, stride):
return math.ceil(float(size) / float(stride))`

**Comment by ComputerMystery** [comment]
It works now!

**Comment by mittlin** [comment]
@ComputerMystery ， Do you  fix the error?

**Comment by ComputerMystery** [comment]
@mittlin Already fixed . Just forced type convert to int for the return`def conv_out_size_same(size, stride): return int(math.ceil(float(size) / float(stride)))`

**Comment by mittlin** [comment]
@ComputerMystery ，thanks

**Comment by maz369** [comment]
Thanks for the suggestions. I applied the suggested change (def conv_out_size_same(size, stride):   return int(math.ceil(float(size) / float(stride))));    but still getting the following error.

/python2.7/site-packages/PIL/Image.py", line 2651, in fromarray
    raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type


Please let me know if you have any suggestion for this error. THANK YOU!

**Comment by Boyle-Coffee** [comment]
@maz369  Hello? Have you solved the problem?

**Comment by ioridev** [comment]
I have a similar problem

/lib/python3.6/site-packages/PIL/Image.py", line 2647, in fromarray
    raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type

**Comment by hjumper** [comment]
> I have a similar problem
> 
> /lib/python3.6/site-packages/PIL/Image.py", line 2647, in fromarray raise TypeError("Cannot handle this data type") TypeError: Cannot handle this data type

hi, may i ask if you have solved this problem?

**Comment by GraceYYJ** [comment]
收到。

**Comment by lihh1023** [comment]
您好：       来信我已收到，我会尽快回复的。
