### ISSUE TITLE
Running is_train on celebA throws the error: 'Tshape' not in list of allowed values: int32, int64

### ISSUE THREAD

**Issue by ProgramItUp** [carpedm20/DCGAN-tensorflow#108]
I followed the installation instructions with Tensorflow 0.12.1 but when I try to train celebA dataset I get the following error.  Anyone experiencing the same thing?

```
$python main.py --dataset celebA --input_height=108 --is_train --is_crop True
Traceback (most recent call last):
  File "main.py", line 96, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "main.py", line 76, in main
    sample_dir=FLAGS.sample_dir)
  File "/home/medgar/my_tensorflow/gans/DCGAN-tensorflow/model.py", line 75, in __init__
    self.build_model()
  File "/home/medgar/my_tensorflow/gans/DCGAN-tensorflow/model.py", line 107, in build_model
    self.G = self.generator(self.z)
  File "/home/medgar/my_tensorflow/gans/DCGAN-tensorflow/model.py", line 359, in generator
    self.z_, [-1, s_h16, s_w16, self.gf_dim * 8])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 2448, in reshape
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 582, in apply_op
    _Attr(op_def, input_arg.type_attr))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: DataType float32 for attr 'Tshape' not in list of allowed values: int32, int64
```

**Comment by 821760408-sp** [comment]
Cast `s_h16` and `s_w16` to int by doing `int(s_h16)` and `int(s_w16`. `tf.reshape()` don't take float as argument.

**Comment by pbcquoc** [comment]
@821760408-sp  and replace `labels` with `targets` in line 119

**Comment by ProgramItUp** [comment]
I created a pull request that fixes problem.

[https://github.com/carpedm20/DCGAN-tensorflow/pull/109](https://github.com/carpedm20/DCGAN-tensorflow/pull/109)

**Comment by leotam** [comment]
These changes result in:

`File "main.py", line 96, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 76, in main
    sample_dir=FLAGS.sample_dir)
  File "/home/DCGAN-tensorflow/model.py", line 75, in __init__
    self.build_model()
  File "/home/DCGAN-tensorflow/model.py", line 107, in build_model
    self.G = self.generator(self.z)
  File "/home/DCGAN-tensorflow/model.py", line 363, in generator
    h0, [self.batch_size, s_h8, s_w8, self.gf_dim*4], name='g_h1', with_w=True)
  File "/home/DCGAN-tensorflow/ops.py", line 75, in deconv2d
    strides=[1, d_h, d_w, 1])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1077, in conv2d_transpose
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 489, in conv2d_backprop_input
    data_format=data_format, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 509, in apply_op
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'input_sizes' of 'Conv2DBackpropInput' Op has type float32 that does not match expected type of int32.`

At least for TF RC2.1.0

**Comment by bywangxp** [comment]
same question how deal?

**Comment by carpedm20** [comment]
Fixed this with 3d7395a. Try again please.
