### ISSUE TITLE
Error while downloading the dataset

### ISSUE THREAD

**Issue by SerhanGul** [carpedm20/DCGAN-tensorflow#11]
When I try to download the dataset, I get a KeyError about content-length. What might be the cause of it? Below is error message:

```
$ python download.py --datasets celebA
Traceback (most recent call last):
  File "download.py", line 121, in <module>
    download_celeb_a('./data')
  File "download.py", line 65, in download_celeb_a
    filepath = download(url, dirpath)
  File "download.py", line 30, in download
    filesize = int(u.headers["Content-Length"])
  File "/home/guel/anaconda/lib/python2.7/rfc822.py", line 393, in __getitem__
    return self.dict[name.lower()]
KeyError: 'content-length'
```

**Comment by crizCraig** [comment]
There are new sources on http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html

Google Drive:
https://drive.google.com/open?id=0B7EVK8r0v71pWEZsZE9oNnFzTm8

Baidu:
http://pan.baidu.com/s/1eSNpdRG
