### ISSUE TITLE
ValueError: None values not supported.

### ISSUE THREAD

**Issue by Aceb1shmael** [carpedm20/DCGAN-tensorflow#117]
Hi.
An error appear when i run
 `python main.py --dataset mnist --input_height=28 --output_height=28 --c_dim=1 --is_train`

Traceback (most recent call last):
  File "main.py", line 96, in <module>
    tf.app.run()
  File "D:\Applications\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 62, in main
    sample_dir=FLAGS.sample_dir)
  File "D:\ML\GAN\model.py", line 75, in __init__
    self.build_model()
  File "D:\ML\GAN\model.py", line 124, in build_model
    sigmoid_cross_entropy_with_logits(self.D_logits, tf.ones_like(self.D)))
  File "D:\Applications\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1398, in reduce_mean
    _ReductionDims(input_tensor, axis, reduction_indices),
  File "D:\Applications\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1247, in _ReductionDims
    return range(0, array_ops.rank(x))
  File "D:\Applications\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 373, in rank
    return rank_internal(input, name, optimize=True)
  File "D:\Applications\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 393, in rank_internal
    input_tensor = ops.convert_to_tensor(input)
  File "D:\Applications\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 651, in convert_to_tensor
    as_ref=False)
  File "D:\Applications\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "D:\Applications\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "D:\Applications\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "D:\Applications\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 360, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

Thanks for any help

**Comment by asispatra** [comment]
The following changes in model.py works fine for me.
```
117     def sigmoid_cross_entropy_with_logits(x, y):
118       try:
119        - tf.nn.sigmoid_cross_entropy_with_logits(logits=x, labels=y)
119        + return tf.nn.sigmoid_cross_entropy_with_logits(logits=x, labels=y)
120       except:
121        - tf.nn.sigmoid_cross_entropy_with_logits(logits=x, targets=y)
121        + return tf.nn.sigmoid_cross_entropy_with_logits(logits=x, targets=y)
```
Duplicate #115

**Comment by Aceb1shmael** [comment]
@asispatra  it works! 
thank you

**Comment by padmasreenagarajan** [comment]
Hi...Im facing the following error when converting Mobilenetv3 onnx model to tensorflow..
File "C:/Users/mobis/PycharmProjects/mbv3/Scripts/convert_to_onnx.py", line 252, in <module>
    tf_rep = prepare(onnx_model)  # prepare tf representation
  File "C:\Users\mobis\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx_tf\backend.py", line 65, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "C:\Users\mobis\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx_tf\backend.py", line 85, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "C:\Users\mobis\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx_tf\backend.py", line 143, in _onnx_graph_to_tensorflow_rep
    onnx_node, tensor_dict, handlers, opset=opset, strict=strict)
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx_tf\backend.py", line 238, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx_tf\handlers\handler.py", line 61, in handle
    return ver_handle(node, **kwargs)
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx_tf\handlers\backend\slice.py", line 56, in version_10
    input_tensor_shape = tf.constant(input_tensor.shape.dims, ends.dtype)
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 161, in constant_v1
    allow_broadcast=False)
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 265, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\framework\tensor_util.py", line 437, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

Please guide me in solving this! @asispatra

**Comment by asispatra** [comment]
@padmasreenagarajan, it looks like the code(`convert_to_onnx.py`) you are running does not belong to this repo.

You should look at the actual code in `convert_to_onnx.py`.

Thanks

**Comment by padmasreenagarajan** [comment]
The error disappeared when i upgraded my torch version to 1.5
Thank you @asispatra
