### ISSUE TITLE
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

### ISSUE THREAD

**Issue by pandamax** [carpedm20/DCGAN-tensorflow#120]
Configuration：tensorflow 0.12.1, python3.4.3 ,ubuntu14.04
I have successfully run **python download.py mnist** and got the mnist data.but when I ran **python download.py celebA**t ,there was an error : 
File "/usr/lib/python3.4/urllib/request.py", line 1182, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1125, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1163, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1121, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 951, in _send_output
    self.send(msg
  File "/usr/lib/python3.4/http/client.py", line 886, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 1260, in connect
    super().connect()
  File "/usr/lib/python3.4/http/client.py", line 863, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python3.4/socket.py", line 512, in create_connection
    raise err
  File "/usr/lib/python3.4/socket.py", line 503, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "download.py", line 140, in <module>
    download_celeb_a('./data')
  File "download.py", line 65, in download_celeb_a
    filepath = download(url, dirpath)
  File "download.py", line 28, in download
    u = urllib.request.urlopen(url)
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1225, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.4/urllib/request.py", line 1184, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

anyone has the same error?could someone teach me how to fix it,please?thx a lot!

**Comment by pandamax** [comment]
Q2: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by leakyrelu** [comment]
same problem encountered

**Comment by pandamax** [comment]
Have you fixed it?could you please teach me how to solve it?thx very much!

**Comment by leakyrelu** [comment]
I am also in China, the problem is probably the great firewall, maybe try VPN to download celebA, mnist is working fine, btw I also live in wuhan- study in wudaa, nice to meet you

**Comment by pandamax** [comment]
Thanks,nice to meet u,too. I am a newbie in Deep Learning and not very familiar with Linux system.Are you an undergraduate?I study in CUG;  Can I have your wechat or QQ if you don't mind?

**Comment by pandamax** [comment]
I run the code"python3 main.py --dataset mnist --input_height=28 --output_height=28 --c_dim=1 --is_train" the result is here .it seemed that something is wrong
~/DC-GAN/DCGAN-tensorflow-master/DCGAN-tensorflow-master$ python3 main.py --dataset mnist --input_height=28 --output_height=28 --c_dim=1 --is_train
{'batch_size': 64,
 'beta1': 0.5,
 'c_dim': 1,
 'checkpoint_dir': 'checkpoint',
 'dataset': 'mnist',
 'epoch': 25,
 'input_fname_pattern': '*.jpg',
 'input_height': 28,
 'input_width': None,
 'is_crop': False,
 'is_train': True,
 'learning_rate': 0.0002,
 'output_height': 28,
 'output_width': None,
 'sample_dir': 'samples',
 'train_size': inf,
 'visualize': False}
Traceback (most recent call last):
  File "main.py", line 96, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "main.py", line 62, in main
    sample_dir=FLAGS.sample_dir)
  File "/home/lambor/DC-GAN/DCGAN-tensorflow-master/DCGAN-tensorflow-master/model.py", line 75, in __init__
    self.build_model()
  File "/home/lambor/DC-GAN/DCGAN-tensorflow-master/DCGAN-tensorflow-master/model.py", line 99, in build_model
    self.G = self.generator(self.z, self.y)
  File "/home/lambor/DC-GAN/DCGAN-tensorflow-master/DCGAN-tensorflow-master/model.py", line 385, in generator
    z = concat([z, y], 1)
  File "/home/lambor/DC-GAN/DCGAN-tensorflow-master/DCGAN-tensorflow-master/ops.py", line 27, in concat
    return tf.concat(tensors, axis, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/array_ops.py", line 331, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 566, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/constant_op.py", line 179, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/constant_op.py", line 162, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/tensor_util.py", line 332, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/tensor_util.py", line 272, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by stoneyang** [comment]
@pandamax CelebA provides alternative link to baidudisk. See their official website for details.

**Comment by woshidaerduotu99** [comment]
@pandamax  
 have you solved this problem?Can you tell me this method?

**Comment by heyali** [comment]
大家都是中国人，用中文可以吗

**Comment by tianzhuotao** [comment]
emmmm我在看tensorflow的tutorial碰到了这个问题。。。。。欢笑声中打出了gg

**Comment by liuliuxiansheng** [comment]
@heyali 哈哈哈哈，不自觉地笑出声

**Comment by crazyxu** [comment]
你需要一个代理
```
#...
import socket
import socks #PySocks
socks.set_default_proxy(socks.SOCKS5, "127.0.0.1", 1080)
socket.socket = socks.socksocket
mnist = input_data.read_data_sets('MNIST_DATA', one_hot=True)
#...
```

**Comment by hutiaotiao** [comment]
你们问题解决了吗？能教一教我吗？
