### ISSUE TITLE
ValueError: None values not supported.

### ISSUE THREAD

**Issue by MiluAnn** [carpedm20/DCGAN-tensorflow#121]
```
Traceback (most recent call last):
  File "main.py", line 96, in <module>
    tf.app.run()
  File "/home/maxiaosha/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 62, in main
    sample_dir=FLAGS.sample_dir)
  File "/home/maxiaosha/test/DCGAN-tensorflow/model.py", line 75, in __init__
    self.build_model()
  File "/home/maxiaosha/test/DCGAN-tensorflow/model.py", line 124, in build_model
    sigmoid_cross_entropy_with_logits(self.D_logits, tf.ones_like(self.D)))
  File "/home/maxiaosha/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 1398, in reduce_mean
    _ReductionDims(input_tensor, axis, reduction_indices),
  File "/home/maxiaosha/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 1247, in _ReductionDims
    return range(0, array_ops.rank(x))
  File "/home/maxiaosha/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 373, in rank
    return rank_internal(input, name, optimize=True)
  File "/home/maxiaosha/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 393, in rank_internal
    input_tensor = ops.convert_to_tensor(input)
  File "/home/maxiaosha/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 651, in convert_to_tensor
    as_ref=False)
  File "/home/maxiaosha/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/maxiaosha/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/maxiaosha/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/maxiaosha/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 360, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

```
hello！
I downloaded the mnist dataset according to your method, but the following question occurs during training: ValueError: None values not supported.
I try to use my own data set, but still the same error.
Then, I give input_width and output_width assignment, and then training, the same error: None values not supported.
I used tensorflow1.0, Python 2.7.13, Anaconda 4.3.0.
How to solve?

**Comment by carpedm20** [comment]
This is fixed by #118!
