### ISSUE TITLE
Training using celebA dataset fails with error: Type mismatch: expected int32, got float 

### ISSUE THREAD

**Issue by iftekharanam** [carpedm20/DCGAN-tensorflow#123]
### Here is the output

{'batch_size': 64,
 'beta1': 0.5,
 'c_dim': 3,
 'checkpoint_dir': 'checkpoint',
 'dataset': 'celebA',
 'epoch': 25,
 'input_fname_pattern': '*.jpg',
 'input_height': 108,
 'input_width': None,
 'is_crop': True,
 'is_train': False,
 'learning_rate': 0.0002,
 'output_height': 64,
 'output_width': None,
 'sample_dir': 'samples',
 'train_size': inf,
 'visualize': False}
Traceback (most recent call last):
  File "/home/aanam/dcgan/DCGAN-tensorflow/main.py", line 96, in <module>
    tf.app.run()
  File "/public/apps/python/2.7.10/gcc.4.4.7/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/aanam/dcgan/DCGAN-tensorflow/main.py", line 76, in main
    sample_dir=FLAGS.sample_dir)
  File "/home/aanam/dcgan/DCGAN-tensorflow/model.py", line 75, in __init__
    self.build_model()
  File "/home/aanam/dcgan/DCGAN-tensorflow/model.py", line 107, in build_model
    self.G = self.generator(self.z)
  File "/home/aanam/dcgan/DCGAN-tensorflow/model.py", line 359, in generator
    self.z_, [-1, s_h16, s_w16, self.gf_dim * 8])
  File "/public/apps/python/2.7.10/gcc.4.4.7/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1758, in reshape
    name=name)
  File "/public/apps/python/2.7.10/gcc.4.4.7/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 454, in apply_op
    as_ref=input_arg.is_ref)
  File "/public/apps/python/2.7.10/gcc.4.4.7/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 628, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/public/apps/python/2.7.10/gcc.4.4.7/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 180, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/public/apps/python/2.7.10/gcc.4.4.7/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 163, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/public/apps/python/2.7.10/gcc.4.4.7/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 353, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/public/apps/python/2.7.10/gcc.4.4.7/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 290, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got 4.0 of type 'float' instead.

**Comment by paolorota** [comment]
Similar here:

```
Please switch to tf.summary.histogram. Note that tf.summary.histogram uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on their scope.
Traceback (most recent call last):
  File "main.py", line 96, in <module>
    tf.app.run()
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "main.py", line 76, in main
    sample_dir=FLAGS.sample_dir)
  File "/home/myuser/Workspace/DCGAN-tensorflow-master/model.py", line 75, in __init__
    self.build_model()
  File "/home/myuser/Workspace/DCGAN-tensorflow-master/model.py", line 107, in build_model
    self.G = self.generator(self.z)
  File "/home/myuser/Workspace/DCGAN-tensorflow-master/model.py", line 363, in generator
    h0 = tf.nn.relu(self.g_bn0(self.h0))
  File "/home/myuser/Workspace/DCGAN-tensorflow-master/ops.py", line 37, in __call__
    return tf.contrib.layers.batch_norm(x,
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/__init__.py", line 35, in __getattr__
    contrib = importlib.import_module('tensorflow.contrib')
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/contrib/__init__.py", line 27, in <module>
    from tensorflow.contrib import factorization
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/contrib/factorization/__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/contrib/factorization/python/ops/gmm.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/__init__.py", line 66, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 27, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 269, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.classifier import Classifier
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/classifier.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 52, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 22, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "/usr/local/lib/python3.5/dist-packages/dask/dataframe/__init__.py", line 3, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/usr/local/lib/python3.5/dist-packages/dask/dataframe/core.py", line 12, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.5/dist-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat.numpy import *
  File "/usr/local/lib/python3.5/dist-packages/pandas/compat/__init__.py", line 357, in <module>
    from dateutil import parser as _date_parser
  File "/usr/local/lib/python3.5/dist-packages/dateutil/parser.py", line 158
    l.append("%s=%s" % (attr, `value`))
                              ^
SyntaxError: invalid syntaxn3.5/dist-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat.numpy import *
  File "/usr/local/lib/python3.5/dist-packages/pandas/compat/__init__.py", line 357, in <module>
    from dateutil import parser as _date_parser
  File "/usr/local/lib/python3.5/dist-packages/dateutil/parser.py", line 158
    l.append("%s=%s" % (attr, `value`))
                              ^
SyntaxError: invalid syntax

```
