### ISSUE TITLE
Error training both celebA and mnist. model.py:[363]

### ISSUE THREAD

**Issue by paolorota** [carpedm20/DCGAN-tensorflow#125]
Problem while training:

`main.py --dataset celebA --input_height=108 --is_crop True`

Resulting in:

```
Traceback (most recent call last):
  File "/home/myuser/Workspace/DCGAN-tensorflow-master/main.py", line 96, in <module>
    tf.app.run()
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/myuser/Workspace/DCGAN-tensorflow-master/main.py", line 76, in main
    sample_dir=FLAGS.sample_dir)
  File "/home/myuser/Workspace/DCGAN-tensorflow-master/model.py", line 75, in __init__
    self.build_model()
  File "/home/myuser/Workspace/DCGAN-tensorflow-master/model.py", line 107, in build_model
    self.G = self.generator(self.z)
  File "/home/myuser/Workspace/DCGAN-tensorflow-master/model.py", line 363, in generator
    h0 = tf.nn.relu(self.g_bn0(self.h0))
  File "/home/myuser/Workspace/DCGAN-tensorflow-master/ops.py", line 37, in __call__
    return tf.contrib.layers.batch_norm(x,
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/__init__.py", line 35, in __getattr__
    contrib = importlib.import_module('tensorflow.contrib')
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/contrib/__init__.py", line 27, in <module>
    from tensorflow.contrib import factorization
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/contrib/factorization/__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/contrib/factorization/python/ops/gmm.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/__init__.py", line 66, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 27, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 269, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.classifier import Classifier
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/classifier.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 52, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 22, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/home/myuser/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "/usr/local/lib/python3.5/dist-packages/dask/dataframe/__init__.py", line 3, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/usr/local/lib/python3.5/dist-packages/dask/dataframe/core.py", line 12, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.5/dist-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat.numpy import *
  File "/usr/local/lib/python3.5/dist-packages/pandas/compat/__init__.py", line 357, in <module>
    from dateutil import parser as _date_parser
  File "/usr/local/lib/python3.5/dist-packages/dateutil/parser.py", line 158
    l.append("%s=%s" % (attr, `value`))
                              ^
SyntaxError: invalid syntax
```

Any suggestion?

**Comment by carpedm20** [comment]
Looks like this is a python3 related bug.
