### ISSUE TITLE
scipy saving image error

### ISSUE THREAD

**Issue by tangfucius** [carpedm20/DCGAN-tensorflow#154]
Anyone also having this problem?

Traceback (most recent call last):
  File "main.py", line 99, in <module>
    tf.app.run()
  File "/home/kf/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 96, in main
    visualize(sess, dcgan, FLAGS, OPTION)
  File "/mnt/c/Users/KF/Downloads/DCGAN-tensorflow/utils.py", line 183, in visualize
    save_images(samples, [image_frame_dim, image_frame_dim], './samples/test_arange_%s.png' % (idx))
  File "/mnt/c/Users/KF/Downloads/DCGAN-tensorflow/utils.py", line 33, in save_images
    return imsave(inverse_transform(images), size, image_path)
  File "/mnt/c/Users/KF/Downloads/DCGAN-tensorflow/utils.py", line 55, in imsave
    return scipy.misc.imsave(path, merge(images, size))
  File "/home/kf/anaconda3/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 195, in imsave
    im = toimage(arr, channel_axis=2)
  File "/home/kf/anaconda3/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 287, in toimage
    raise ValueError("'arr' does not have a suitable array shape for "
ValueError: 'arr' does not have a suitable array shape for any mode.

The error occurs in both training mode and existing model mode. I am running TF on Bash on Windows, not sure if that could be causing a problem.

**Comment by viligabi** [comment]
This is due to scipy.misc.imsave function can handle specific image matrices only (with shape HxW, HxWx3, HxWx4).
I've corrected this issue in [this pull request](https://github.com/carpedm20/DCGAN-tensorflow/pull/152)

**Comment by tangfucius** [comment]
Works, awesome! Thanks!

**Comment by carpedm20** [comment]
#152 merged.

**Comment by GAIYA2050** [comment]
what's means?
