### ISSUE TITLE
AttributeError: 'module' object has no attribute 'imread'

### ISSUE THREAD

**Issue by amineHorseman** [carpedm20/DCGAN-tensorflow#16]
Hello, 
I just installed Tensorflow and it seems that there's a problem. I got an error when I executed the script with default parameters:
`python main.py --dataset celebA --is_train True --is_crop True`

**Configuration:**
- OS: Ubuntu 16.04, 64 bits
- Python version 2.7
- Anaconda 2-4.0.0
- Tensorflow 0.8.0 (installed in conda env)

**Output:**
```
{'batch_size': 64,
 'beta1': 0.5,
 'checkpoint_dir': 'checkpoint',
 'dataset': 'celebA',
 'epoch': 25,
 'image_size': 108,
 'is_crop': True,
 'is_train': True,
 'learning_rate': 0.0002,
 'sample_dir': 'samples',
 'train_size': inf}
WARNING:tensorflow:Passing a `GraphDef` to the SummaryWriter is deprecated. Pass a `Graph` object instead, such as `sess.graph`.
Traceback (most recent call last):
  File "main.py", line 54, in <module>
    tf.app.run()
  File "/home/amine/anaconda2/envs/tensorflow_cpu/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "main.py", line 39, in main
    dcgan.train(FLAGS)
  File "/home/amine/workspace/DCGAN-tensorflow/model.py", line 125, in train
    sample = [get_image(sample_file, self.image_size, is_crop=self.is_crop) for sample_file in sample_files]
  File "/home/amine/workspace/DCGAN-tensorflow/utils.py", line 17, in get_image
    return transform(imread(image_path), image_size, is_crop)
  File "/home/amine/workspace/DCGAN-tensorflow/utils.py", line 23, in imread
    return scipy.misc.imread(path).astype(np.float)
AttributeError: 'module' object has no attribute 'imread'
```

**Comment by mfigurnov** [comment]
This may be caused by https://github.com/tensorflow/tensorflow/issues/1992 . A simple fix is to add `import scipy.misc` as the first line to `main.py`. Also, make sure you have installed the Pillow package: `pip install Pillow`.

**Comment by amineHorseman** [comment]
Ok, so it's by adding `import scipy.misc` there no AttributeError, but still, I got an error because the bias was not initialize, so I added `init_op = tf.initialize_all_variables()` in main.py, line 44.
And now, I'm getting another error:
```
(tensorflow_cpu)amine@Destructor:~/workspace/DCGAN-tensorflow$ python main.py --dataset celebA --is_train True --is_crop True
{'batch_size': 64,
 'beta1': 0.5,
 'checkpoint_dir': 'checkpoint',
 'dataset': 'celebA',
 'epoch': 25,
 'image_size': 108,
 'is_crop': True,
 'is_train': True,
 'learning_rate': 0.0002,
 'sample_dir': 'samples',
 'train_size': inf}
WARNING:tensorflow:Passing a `GraphDef` to the SummaryWriter is deprecated. Pass a `Graph` object instead, such as `sess.graph`.
 [*] Reading checkpoints...
 [!] Load failed...
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    tf.app.run()
  File "/home/amine/anaconda2/envs/tensorflow_cpu/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "main.py", line 40, in main
    dcgan.train(FLAGS)
  File "/home/amine/workspace/DCGAN-tensorflow/model.py", line 150, in train
    feed_dict={ self.images: batch_images, self.z: batch_z })
  File "/home/amine/anaconda2/envs/tensorflow_cpu/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/home/amine/anaconda2/envs/tensorflow_cpu/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 564, in _run
    feed_dict_string, options, run_metadata)
  File "/home/amine/anaconda2/envs/tensorflow_cpu/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 637, in _do_run
    target_list, options, run_metadata)
  File "/home/amine/anaconda2/envs/tensorflow_cpu/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 659, in _do_call
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: tags and values not the same shape: [] != [64,1] (tag 'd_loss_real')
	 [[Node: ScalarSummary = ScalarSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](ScalarSummary/tags, logistic_loss)]]
Caused by op u'ScalarSummary', defined at:
  File "main.py", line 55, in <module>
    tf.app.run()
  File "/home/amine/anaconda2/envs/tensorflow_cpu/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "main.py", line 37, in main
    dataset_name=FLAGS.dataset, is_crop=FLAGS.is_crop, checkpoint_dir=FLAGS.checkpoint_dir)
  File "/home/amine/workspace/DCGAN-tensorflow/model.py", line 62, in __init__
    self.build_model()
  File "/home/amine/workspace/DCGAN-tensorflow/model.py", line 91, in build_model
    self.d_loss_real_sum = tf.scalar_summary("d_loss_real", self.d_loss_real)
  File "/home/amine/anaconda2/envs/tensorflow_cpu/lib/python2.7/site-packages/tensorflow/python/ops/logging_ops.py", line 234, in scalar_summary
    val = gen_logging_ops._scalar_summary(tags=tags, values=values, name=scope)
  File "/home/amine/anaconda2/envs/tensorflow_cpu/lib/python2.7/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 181, in _scalar_summary
    name=name)
  File "/home/amine/anaconda2/envs/tensorflow_cpu/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "/home/amine/anaconda2/envs/tensorflow_cpu/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/amine/anaconda2/envs/tensorflow_cpu/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1154, in __init__
    self._traceback = _extract_stack()
```

**Comment by hi0001234d** [comment]
For me `pip install Pillow` did the fix

**Comment by vivekmathema** [comment]
thank you for the code
