### ISSUE TITLE
Trying to share variable discriminator/d_h3_lin/Matrix

### ISSUE THREAD

**Issue by tusik** [carpedm20/DCGAN-tensorflow#167]
```
{'batch_size': 64,
 'beta1': 0.5,
 'checkpoint_dir': 'checkpoint',
 'crop': False,
 'dataset': 'faces',
 'epoch': 25,
 'input_fname_pattern': '*.jpg',
 'input_height': 96,
 'input_width': 96,
 'learning_rate': 0.0002,
 'output_height': 64,
 'output_width': 64,
 'sample_dir': 'samples',
 'train': True,
 'train_size': inf,
 'visualize': False}
2017-05-02 18:44:49.160149: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-02 18:44:49.160180: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-02 18:44:49.160190: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-05-02 18:44:49.160197: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-02 18:44:49.160204: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "main.py", line 97, in <module>
    tf.app.run()
  File "/usr/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 75, in main
    sample_dir=FLAGS.sample_dir)
  File "/opt/DCGAN-tensorflow/model.py", line 82, in __init__
    self.build_model()
  File "/opt/DCGAN-tensorflow/model.py", line 118, in build_model
    self.D_, self.D_logits_ = self.discriminator(self.G, reuse=True)
  File "/opt/DCGAN-tensorflow/model.py", line 332, in discriminator
    h4 = linear(tf.reshape(h3, [self.batch_size, -1]), 1, 'd_h3_lin')
  File "/opt/DCGAN-tensorflow/ops.py", line 98, in linear
    tf.random_normal_initializer(stddev=stddev))
  File "/usr/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1049, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 948, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 356, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 341, in _true_getter
    use_resource=use_resource)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 658, in _get_single_variable
    found_var.get_shape()))
ValueError: Trying to share variable discriminator/d_h3_lin/Matrix, but specified shape (8192, 1) and found shape (18432, 1).

```
My commond is 
```
python main.py --dataset faces --input_height=96 --output_height=64 --train
```
my data file size is 96*96,i'm try many time but always this error.
can you help me?

**Comment by zhanary** [comment]
I have the same problem :(

**Comment by chunfengshiliburuni** [comment]
I have the same problem.
Can you help me?

**Comment by chunfengshiliburuni** [comment]
When I run the  download.py,there is another problem:
usage: download.py [-h] N [N ...]
download.py: error: the following arguments are required: N
Can you help me?Please

**Comment by tusik** [comment]
@chunfengshiliburuni 
sorry,i'm using my date.I haven't try download data.And this is still not work on my computer

**Comment by chunfengshiliburuni** [comment]
@tusik 
thank you anyway

**Comment by Lishiqing** [comment]
@chunfengshiliburuni In the `download.py`, it tells you that `'datasets', metavar='N', type=str, nargs='+', choices=['celebA', 'lsun', 'mnist']` .So the wrong is you didn't choose one or more specific dataset

**Comment by georgiazhang** [comment]
@chunfengshiliburuni  Hi ,did you solve the problem?

**Comment by kabrio** [comment]
@tusik your data file size is 96*64 does mean that your images are 96 px * 64 px ? 
if so try square images!

**Comment by kabrio** [comment]
@chunfengshiliburuni for example: you have to say "download.py mnist" to download MNIST dataset

**Comment by tusik** [comment]
@kabrio The images are 96*96 not 96*64, it's my mistake.Thank you for your advice.

**Comment by chunfengshiliburuni** [comment]
@kabrio  
Thank you very much. I solved it.

**Comment by chunfengshiliburuni** [comment]
@kabrio  Thank you very much. I solved it.

**Comment by chunfengshiliburuni** [comment]
@Lishiqing  Thank you. I solved the problem.

**Comment by shinmai** [comment]
I'm having a similar issue, and don't get what I'm doing wrong.

my command line is

> python main.py --dataset apkort --input_height=108 --output_height=64 --train

```
{'batch_size': 64,
 'beta1': 0.5,
 'checkpoint_dir': 'checkpoint',
 'crop': False,
 'dataset': 'apkort',
 'epoch': 25,
 'input_fname_pattern': '*.jpg',
 'input_height': 108,
 'input_width': None,
 'learning_rate': 0.0002,
 'output_height': 64,
 'output_width': None,
 'sample_dir': 'samples',
 'train': True,
 'train_size': inf,
 'visualize': False}
Traceback (most recent call last):
  File "main.py", line 97, in <module>
    tf.app.run()
  File "C:\Python\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 75, in main
    sample_dir=FLAGS.sample_dir)
  File "C:\dcgan\DCGAN-tensorflow\model.py", line 82, in __init__
    self.build_model()
  File "C:\dcgan\DCGAN-tensorflow\model.py", line 118, in build_model
    self.D_, self.D_logits_ = self.discriminator(self.G, reuse=True)
  File "C:\dcgan\DCGAN-tensorflow\model.py", line 332, in discriminator
    h4 = linear(tf.reshape(h3, [self.batch_size, -1]), 1, 'd_h3_lin')
  File "C:\dcgan\DCGAN-tensorflow\ops.py", line 98, in linear
    tf.random_normal_initializer(stddev=stddev))
  File "C:\Python\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1049, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "C:\Python\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 948, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "C:\Python\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 356, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "C:\Python\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 341, in _true_getter
    use_resource=use_resource)
  File "C:\Python\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 658, in _get_single_variable
    found_var.get_shape()))
ValueError: Trying to share variable discriminator/d_h3_lin/Matrix, but specified shape (8192, 1) and found shape (25088, 1).
```

My images are jpeg files named 0001.jpg - 0100.jpg all sized 108x108 px.

I'm sure I'm missing something super obvious, and would appreciate any advice as to what I'm doing wrong.

**Comment by kabrio** [comment]
@shinmai dunno, did you try setting output height to same as input height?

**Comment by LittlePandaSea** [comment]
Change your arguments as: python main.py --image_size 96 --output_size 48 --dataset faces --crop True --train True --epoch 300.
**Not**   --is_crop True --is_train True --epoch 300. 
The formats of the input arguments is changed.

**Comment by tusik** [comment]
@LittlePandaSea It's works ! Thank you~
