### ISSUE TITLE
ValueError: Cannot feed value of shape (64, 80, 512) for Tensor 'real_images:0', which has shape '(64, 80, 512, 512)'

### ISSUE THREAD

**Issue by zhanary** [carpedm20/DCGAN-tensorflow#174]
When I use my own dataset (512*80 bmp 8bit), I put in
`python main.py --input_height 80 --input_width 512 --output_height 80 --output_width 512 --dataset eye --crop --train --epoch 30 --input_fname_pattern "*.bmp"`
and the error is
`Traceback (most recent call last):
  File "main.py", line 97, in <module>
    tf.app.run()
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 80, in main
    dcgan.train(FLAGS)
  File "C:\Program Files\Anaconda3\Lib\site-packages\tensorflow\examples\DCGAN\model.py", line 265, in train
    feed_dict={ self.inputs: batch_images, self.z: batch_z })
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 778, in run
    run_metadata_ptr)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 961, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (64, 80, 512) for Tensor 'real_images:0', which has shape '(64, 80, 512, 512)'`

I try to set the c_dim=1, but it not work.
What should I do?

Thank you ~

**Comment by MaxChu719** [comment]
the current code has bug in gray scale image.  See the PR #173 for the bug fixed!
