### ISSUE TITLE
Generate more number of images

### ISSUE THREAD

**Issue by hellorp1990** [carpedm20/DCGAN-tensorflow#183]
I have trained the code for my own dataset.My dataset has 200 images. and only 100 images are generated during the test procedure. But how can I generate more number of images (e.g, 1000) during the test procedure? 
I didn't understand where should I change in the code to make this happen.

**Comment by ppwwyyxx** [comment]
https://github.com/carpedm20/DCGAN-tensorflow/search?l=Python&q=100&type=&utf8=%E2%9C%93
In utils.py

**Comment by hellorp1990** [comment]
Hi,
@ppwwyyxx I changed the shown lines, but now its giving error. I changed the 100 to 150.

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [150,8192] rhs shape= [100,8192]

**Comment by mohanadkaleia** [comment]
Aside question, are you getting good results by training with only 200 images?

**Comment by hellorp1990** [comment]
@mohanadkaleia no i didn't.

**Comment by zqclinux** [comment]
Hello, I hava a trouble.In my train_set,I can get perfect picture.But,when I use trained-model to generate some picture,its so bad....  I want to know if I don't use the model.

**Comment by rp2017** [comment]
@ppwwyyxx hey .. i also faced the same problem, only 100 images are generating. I followed the line you asked to change in utils.py... but it is giving me error. Any help??

**Comment by asispatra** [comment]
PR #216 created. Please verify it.

**Comment by hellorp1990** [comment]
@ppwwyyxx  i followed your solution, but it didn't run for more than 100. it was working, if I want to generate 10 images. but when I put 110, it gave me following error

Traceback (most recent call last):
  File "main.py", line 97, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "main.py", line 94, in main
    visualize(sess, dcgan, FLAGS, OPTION)
  File "/Users/rahulpaul/Desktop/keras/DCGAN-tensorflow-master/utils.py", line 184, in visualize
    z[idx] = values[kdx]
IndexError: index 100 is out of bounds for axis 0 with size 100
