### ISSUE TITLE
What does this mean and how can I train my own images

### ISSUE THREAD

**Issue by BLCKPSTV** [carpedm20/DCGAN-tensorflow#186]
I've inputted following with the correct map with images.

```
python main.py --dataset=test --input_fname_pattern="*.png" --train
{'batch_size': 64,
 'beta1': 0.5,
 'checkpoint_dir': 'checkpoint',
 'crop': False,
 'dataset': 'test',
 'epoch': 25,
 'input_fname_pattern': '*.png',
 'input_height': 108,
 'input_width': None,
 'learning_rate': 0.0002,
 'output_height': 64,
 'output_width': None,
 'sample_dir': 'samples',
 'train': True,
 'train_size': inf,
 'visualize': False}
2017-05-31 22:59:00.428564: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-31 22:59:00.428580: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-31 22:59:00.428585: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-05-31 22:59:00.428588: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-31 22:59:00.428592: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "main.py", line 97, in <module>
    tf.app.run()
  File "/Users/quintendewilde/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 75, in main
    sample_dir=FLAGS.sample_dir)
  File "/Users/quintendewilde/projects/DCGAN-tensorflow/model.py", line 82, in __init__
    self.build_model()
  File "/Users/quintendewilde/projects/DCGAN-tensorflow/model.py", line 118, in build_model
    self.D_, self.D_logits_ = self.discriminator(self.G, reuse=True)
  File "/Users/quintendewilde/projects/DCGAN-tensorflow/model.py", line 332, in discriminator
    h4 = linear(tf.reshape(h3, [self.batch_size, -1]), 1, 'd_h3_lin')
  File "/Users/quintendewilde/projects/DCGAN-tensorflow/ops.py", line 98, in linear
    tf.random_normal_initializer(stddev=stddev))
  File "/Users/quintendewilde/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1049, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/Users/quintendewilde/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 948, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/Users/quintendewilde/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 356, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/Users/quintendewilde/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 341, in _true_getter
    use_resource=use_resource)
  File "/Users/quintendewilde/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 658, in _get_single_variable
    found_var.get_shape()))
ValueError: Trying to share variable discriminator/d_h3_lin/Matrix, but specified shape (8192, 1) and found shape (25088, 1).

```

**Comment by mohanadkaleia** [comment]
you need to use the parameter crop in the end, like this: 
`python main.py --dataset=test --input_fname_pattern="*.png" --train --crop` 
Also try to specify the input height and width, otherwise it will consider the height 108 and crop the image based on that,
