### ISSUE TITLE
[Errno 2] No such file or directory: './data/mnist/train-images-idx3-ubyte'

### ISSUE THREAD

**Issue by Jiangzhonghao** [carpedm20/DCGAN-tensorflow#196]
Hello, I am running main.py of DCGAN, there is an error in the picture. What is this caused? thank you very much.

Traceback (most recent call last):
  File "main.py", line 97, in <module>
    tf.app.run()
  File "/home/jzh0/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 61, in main
    sample_dir=FLAGS.sample_dir)
  File "/home/jzh0/program/DCGAN-tensorflow-master/model.py", line 74, in __init__
    self.data_X, self.data_y = self.load_mnist()
  File "/home/jzh0/program/DCGAN-tensorflow-master/model.py", line 464, in load_mnist
    fd = open(os.path.join(data_dir,'train-images-idx3-ubyte'))
IOError: [Errno 2] No such file or directory: './data/mnist/train-images-idx3-ubyte'

**Comment by zetn** [comment]
I think it is the reason that download.py cannot get mnist train data, so you copy the data you have to the directory! but the name wasn't correct('.' change to '-'). so you should rename the mnist data.

**Comment by Jiangzhonghao** [comment]
The program can run, thank you very much！ @zetn

**Comment by lzh19961031** [comment]
@Jiangzhonghao @zetn I'm sorry, I only got three folders,img_align_celeba which has all the pictures ,img_celeba.7z and img_align_celeba.7z ,how to change the names?

**Comment by Manuel4131** [comment]
Go to here `https://github.com/Manuel4131/GoMNIST/tree/master/data`
and download the mnist data.
Copy the mnist data to `./data/mnist/` (If the directory doesn't exist, create by yourself.)
(Use `gzip -d` command to uncompress the data first)

**Comment by Neeyan** [comment]
I got the same error, but my data name is true. And I save the data at `E:\8\data\mnist`

`Traceback (most recent call last):
  File "main.py", line 99, in <module>
    tf.app.run()

  File "C:\Users\CUGID\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)

  File "C:\Users\CUGID\Anaconda3\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)

  File "C:\Users\CUGID\Anaconda3\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))

  File "main.py", line 63, in main
    sample_dir=FLAGS.sample_dir)

  File "E:\8\model.py", line 74, in __init__
    self.data_X, self.data_y = self.load_mnist()

  File "E:\8\model.py", line 464, in load_mnist
    fd = open(os.path.join(data_dir,'train-images-idx3-ubyte'))

FileNotFoundError: [Errno 2] No such file or directory: './data\\mnist\\train-images-idx3-ubyte'`

**Comment by ahmedshingaly** [comment]
i am still facing same error 

Traceback (most recent call last):
  File "main.py", line 100, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 63, in main
    sample_dir=FLAGS.sample_dir)
  File "C:\Users\USER6459\Documents\python\Tbackend\Kaeroes\DCGAN\model.py", line 74, in __init__
    self.data_X, self.data_y = self.load_mnist()
  File "C:\Users\USER6459\Documents\python\Tbackend\Kaeroes\DCGAN\model.py", line 456, in load_mnist
    fd = open(os.path.join(data_dir,'train-images-idx3-ubyte'))
FileNotFoundError: [Errno 2] No such file or directory: './data\\mnist\\train-images-idx3-ubyte'

**Comment by ManjunathaPrince** [comment]
I also got same error!

Traceback (most recent call last):
  File "C:/Users/MANJUNATHA/PycharmProjects/Recognition/knn.py", line 7, in <module>
    images, labels = mndata.load_training()
  File "C:\Users\MANJUNATHA\AppData\Roaming\Python\Python38\site-packages\mnist\loader.py", line 125, in load_training
    ims, labels = self.load(os.path.join(self.path, self.train_img_fname),
  File "C:\Users\MANJUNATHA\AppData\Roaming\Python\Python38\site-packages\mnist\loader.py", line 247, in load
    with self.opener(path_lbl, 'rb') as file:
  File "C:\Users\MANJUNATHA\AppData\Roaming\Python\Python38\site-packages\mnist\loader.py", line 239, in opener
Loading dataset...
    return open(path_fn, *args, **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: './data/train-labels-idx1-ubyte'

Process finished with exit code 1

**Comment by icewaterice** [comment]
unzip the mnist file and change file name, because the name are wrong.
