### ISSUE TITLE
Generate more number of images

### ISSUE THREAD

**Issue by paultpa** [carpedm20/DCGAN-tensorflow#215]
I have trained the code for my own dataset and only 100 images are generated during the test procedure. But how can I generate more number of images (e.g, 1000) during the test procedure?
I didn't understand where should I change in the code to make this happen. Please help

**Comment by asispatra** [comment]
PR #216 created, Please verify it.

**Comment by hellorp1990** [comment]
@asispatra 
I am using option 1 to generate image and I am running my code like this:

> python main.py --input_height 96 --output_height 48 --dataset /Users/rl/Desktop/keras/DCGAN-tensorflow-master/data/new3/ --crop --epoch 2 --train

**Comment by hellorp1990** [comment]
@asispatra  I changed my code according to your reply. But I just wanted to check to generate 110 images. But after running it is giving me the following error.

[*] Reading checkpoints...
Traceback (most recent call last):
  File "main.py", line 100, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "main.py", line 83, in main
    dcgan.train(FLAGS)
  File "/Users/rahulpaul/Desktop/keras/DCGAN-tensorflow-master/model.py", line 190, in train
    could_load, checkpoint_counter = self.load(self.checkpoint_dir)
  File "/Users/rahulpaul/Desktop/keras/DCGAN-tensorflow-master/model.py", line 526, in load
    self.saver.restore(self.sess, os.path.join(checkpoint_dir, ckpt_name))
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1436, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 717, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 915, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 985, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [110,4608] rhs shape= [100,4608]
	 [[Node: save/Assign_38 = Assign[T=DT_FLOAT, _class=["loc:@generator/g_h0_lin/Matrix"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](generator/g_h0_lin/Matrix, save/restore_slice_38)]]

Caused by op u'save/Assign_38', defined at:
  File "main.py", line 100, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "main.py", line 78, in main
    sample_dir=FLAGS.sample_dir)
  File "/Users/rahulpaul/Desktop/keras/DCGAN-tensorflow-master/model.py", line 82, in __init__
    self.build_model()
  File "/Users/rahulpaul/Desktop/keras/DCGAN-tensorflow-master/model.py", line 150, in build_model
    self.saver = tf.train.Saver()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1077, in __init__
    self.build()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1106, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 704, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 453, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 211, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 45, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2380, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1298, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [110,4608] rhs shape= [100,4608]
	 [[Node: save/Assign_38 = Assign[T=DT_FLOAT, _class=["loc:@generator/g_h0_lin/Matrix"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](generator/g_h0_lin/Matrix, save/restore_slice_38)]]
