### ISSUE TITLE
Error loading checkpoint file NotFoundError KeyDiscriminator

### ISSUE THREAD

**Issue by Noahyt** [carpedm20/DCGAN-tensorflow#230]
I am following the guide at http://bamos.github.io/2016/08/09/deep-completion/ 

When I run `./train-dcgan.py --dataset ./data/your-dataset/aligned --epoch 20`

I get an error (full printout below) indicating that certain tensors were not found in the checkpoint. 

````
2017-10-17 18:04:31.286943: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-17 18:04:31.286965: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-10-17 18:04:31.286971: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-17 18:04:31.286976: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
 [*] Reading checkpoints...
2017-10-17 18:04:47.883423: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key discriminator/d_bn0/moving_variance not found in checkpoint
2017-10-17 18:04:47.883536: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key discriminator/d_bn0/moving_mean not found in checkpoint
2017-10-17 18:04:47.883625: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key discriminator/d_bn0/gamma not found in checkpoint
2017-10-17 18:04:47.888975: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key discriminator/d_bn0/beta not found in checkpoint
2017-10-17 18:04:47.900231: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key discriminator/d_h4_lin/Matrix not found in checkpoint
2017-10-17 18:04:47.900820: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key discriminator/d_h4_lin/bias not found in checkpoint
Traceback (most recent call last):
  File "./train-dcgan.py", line 41, in <module>
    dcgan.train(FLAGS)
  File "/Users/ntoyonaga/Documents/dcgan-completion.tensorflow/model.py", line 174, in train
    if self.load(self.checkpoint_dir):
  File "/Users/ntoyonaga/Documents/dcgan-completion.tensorflow/model.py", line 462, in load
    self.saver.restore(self.sess, ckpt.model_checkpoint_path)
  File "/Users/ntoyonaga/Envs/tensorflow_noah/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/Users/ntoyonaga/Envs/tensorflow_noah/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/Users/ntoyonaga/Envs/tensorflow_noah/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/ntoyonaga/Envs/tensorflow_noah/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/Users/ntoyonaga/Envs/tensorflow_noah/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key discriminator/d_bn0/moving_variance not found in checkpoint
	 [[Node: save/RestoreV2_3 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_3/tensor_names, save/RestoreV2_3/shape_and_slices)]]

Caused by op u'save/RestoreV2_3', defined at:
  File "./train-dcgan.py", line 39, in <module>
    is_crop=False, checkpoint_dir=FLAGS.checkpoint_dir)
  File "/Users/ntoyonaga/Documents/dcgan-completion.tensorflow/model.py", line 81, in __init__
    self.build_model()
  File "/Users/ntoyonaga/Documents/dcgan-completion.tensorflow/model.py", line 130, in build_model
    self.saver = tf.train.Saver(max_to_keep=1)
  File "/Users/ntoyonaga/Envs/tensorflow_noah/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1140, in __init__
    self.build()
  File "/Users/ntoyonaga/Envs/tensorflow_noah/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1172, in build
    filename=self._filename)
  File "/Users/ntoyonaga/Envs/tensorflow_noah/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 688, in build
    restore_sequentially, reshape)
  File "/Users/ntoyonaga/Envs/tensorflow_noah/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/Users/ntoyonaga/Envs/tensorflow_noah/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/Users/ntoyonaga/Envs/tensorflow_noah/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 663, in restore_v2
    dtypes=dtypes, name=name)
  File "/Users/ntoyonaga/Envs/tensorflow_noah/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/Users/ntoyonaga/Envs/tensorflow_noah/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/ntoyonaga/Envs/tensorflow_noah/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Key discriminator/d_bn0/moving_variance not found in checkpoint
	 [[Node: save/RestoreV2_3 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_3/tensor_names, save/RestoreV2_3/shape_and_slices)]]
```
`

**Comment by Noahyt** [comment]
I solved this by deleting all the files in the "checkpoint" directory under `dcgan-completion.tensorflow/checkpoint`.  For some reason the files already there were not complete, but the program was still trying to load them.
