### ISSUE TITLE
image error

### ISSUE THREAD

**Issue by BLCKPSTV** [carpedm20/DCGAN-tensorflow#234]
Hello, 

I've been able to run this with batches of images I made from myself. I know put all those images together and I get constant errors like below. I've already deleted like 30 of those and still they come up.

What does this mean? 

```
python main.py --dataset=folderboxingunclean --input_height=306 --train --crop
{'batch_size': 64,
 'beta1': 0.5,
 'checkpoint_dir': 'checkpoint',
 'crop': True,
 'dataset': 'folderboxingunclean',
 'epoch': 25,
 'input_fname_pattern': '*.jpg',
 'input_height': 306,
 'input_width': None,
 'learning_rate': 0.0002,
 'output_height': 64,
 'output_width': None,
 'sample_dir': 'samples',
 'train': True,
 'train_size': inf,
 'unrolled_lstm': False,
 'visualize': False}
Traceback (most recent call last):
  File "main.py", line 97, in <module>
    tf.app.run()
  File "/home/quinten/anaconda2/envs/carpedm20/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "main.py", line 75, in main
    sample_dir=FLAGS.sample_dir)
  File "/home/quinten/Documents/DCGAN-tensorflow/model.py", line 78, in __init__
    imreadImg = imread(self.data[0]);
  File "/home/quinten/Documents/DCGAN-tensorflow/utils.py", line 39, in imread
    return scipy.misc.imread(path).astype(np.float)
  File "/home/quinten/anaconda2/envs/carpedm20/lib/python2.7/site-packages/scipy/misc/pilutil.py", line 156, in imread
    im = Image.open(name)
  File "/home/quinten/anaconda2/envs/carpedm20/lib/python2.7/site-packages/PIL/Image.py", line 2519, in open
    % (filename if filename else fp))
IOError: cannot identify image file './data/folderboxingunclean/img433.jpg'
```

**Comment by peterkentish** [comment]
Hi, i am having this problem. Did you ever find a fix for it? There was a similar issue on the torch implementation which verified that the file read was successful, and if not it passed over the image. Something similar might help?

**Comment by peterkentish** [comment]
Answering myself but for anyone who has this issue, fixed it by bypassing any read operations that fail. Used the following in model.py around line 208:
 ```
batch_files = self.data[idx*config.batch_size:(idx+1)*config.batch_size]
        try:
          batch = [
              get_image(batch_file,
                        input_height=self.input_height,
                        input_width=self.input_width,
                        resize_height=self.output_height,
                        resize_width=self.output_width,
                        crop=self.crop,
                        grayscale=self.grayscale) for batch_file in batch_files]
          if self.grayscale:
            batch_images = np.array(batch).astype(np.float32)[:, :, :, None]
          else:
            batch_images = np.array(batch).astype(np.float32)
        except:
          print ("failed on batch id: "+ str(batch_idxs))
```
