### ISSUE TITLE
Unable to train model because of python runtime error

### ISSUE THREAD

**Issue by cathybgyz** [carpedm20/DCGAN-tensorflow#235]
Does anyone know why this error occurs? Installed the dependencies from pip3 using python3, as specified in the dependencies folder. 

python request dependency was also not included in the required dependencies section. I recommend the developers of this project create a dependencies.txt file in order to give users visiting this project a complete set of the required dependencies.

Appreciate any help

$ python main.py --dataset mnist --input_height=28 --output_height=28 --train
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import scipy.misc
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\misc\__init__.py", line 53, in <module>
    from scipy.interpolate._pade import pade
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\interpolate\__init__.py", line 176, in <module>
    from .interpolate import *
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\interpolate\interpolate.py", line 20, in <module>
    import scipy.linalg
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\linalg\__init__.py", line 175, in <module>
    from .misc import *
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\linalg\misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\linalg\blas.py", line 155, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed: The specified module could not be found.

**Comment by Ianmcmill** [comment]
I would suggest running this in a virtualenv. Saves you a lot of headaches. There are tutorials how to install virtualenv for Windows. 
You can then create virtual environments with specific versions of all the libraries. Sometimes you need a different version for specific code here on github.
Important: look for how to create virtualenvs with default Python 3.6 64bit.
If you want to test out other nn code here on github, Python36 64bit is necessary almost everywhere.

If you want to be sure to have a deps installaed, check every .py file for import syntax and install them

Also, don't expect the authors to help out on 2-3 year old projects.Yyour questions will probably never be answered. And it is up to you to to crawl through myriad of questions on stackexchange. But eventually in the end you will get the intuition on how to run all this unmaintained code by yourself.
