### ISSUE TITLE
IndexError: list index out of range with custom dataset

### ISSUE THREAD

**Issue by nightfox8** [carpedm20/DCGAN-tensorflow#254]
Hello all,
I am trying to run this on my own dataset of flowers, but I am getting this error,

> $ python main.py --dataset=flowares  --train
> {'batch_size': 64,
>  'beta1': 0.5,
>  'checkpoint_dir': 'checkpoint',
>  'crop': False,
>  'dataset': 'flowares',
>  'epoch': 25,
>  'generate_test_images': 100,
>  'input_fname_pattern': '*.jpg',
>  'input_height': 108,
>  'input_width': None,
>  'learning_rate': 0.0002,
>  'output_height': 64,
>  'output_width': None,
>  'sample_dir': 'samples',
>  'train': True,
>  'train_size': inf,
>  'visualize': False}
> 2018-01-11 18:40:07.522922: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
> Traceback (most recent call last):
>   File "main.py", line 100, in <module>
>     tf.app.run()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
>     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
>   File "main.py", line 78, in main
>     sample_dir=FLAGS.sample_dir)
>   File "/home/sohilparekh/Desktop/HardikC/DCGAN-tensorflow/model.py", line 78, in __init__
>     imreadImg = imread(self.data[0])
> IndexError: list index out of range

**Comment by lulujiang1281** [comment]
请问问题解决了吗，我也是这个问题，如果解决了可以告诉一下解决方法吗，跪谢

**Comment by zlyx525** [comment]
This is because your pictures are not "*.jpg" format, your can set the option according to your own format, like this:
python main.py --dataset=flowares --input_fname_pattern='*.png' --train

**Comment by chengxiqiao** [comment]
My images are all '*.jpg',but i met this problem too

**Comment by 738654805** [comment]
wait！！！dalao come to see!!!

**Comment by changecheng** [comment]
data_dir + dataset = real dir path that store your pictures

**Comment by YuzuruHanyu520** [comment]
Can you solved this problem?

**Comment by jcForDream** [comment]
I meet the problem too.

**Comment by lihh1023** [comment]
您好：       来信我已收到，我会尽快回复的。
