### ISSUE TITLE
Why can't I download the dataset successfully according to the README.md ?

### ISSUE THREAD

**Issue by xzllxls** [carpedm20/DCGAN-tensorflow#256]
D:\workspacePython\DCGAN-tensorflow-master>python download.py mnist celebA
Traceback (most recent call last):
  File "D:\PROGRAMS\Python\Python35\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "D:\PROGRAMS\Python\Python35\lib\site-packages\urllib3\util\connection.py", line 83, in create_connection
    raise err
  File "D:\PROGRAMS\Python\Python35\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PROGRAMS\Python\Python35\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "D:\PROGRAMS\Python\Python35\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "D:\PROGRAMS\Python\Python35\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "D:\PROGRAMS\Python\Python35\lib\site-packages\urllib3\connection.py", line 284, in connect
    conn = self._new_conn()
  File "D:\PROGRAMS\Python\Python35\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x00000000031BFFD0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PROGRAMS\Python\Python35\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "D:\PROGRAMS\Python\Python35\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\PROGRAMS\Python\Python35\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=0B7EVK8r0v71pZjFTYXZWM3FlRnM (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000000031BFFD0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "download.py", line 176, in <module>
    download_celeb_a('./data')
  File "download.py", line 100, in download_celeb_a
    download_file_from_google_drive(drive_id, save_path)
  File "download.py", line 58, in download_file_from_google_drive
    response = session.get(URL, params={ 'id': id }, stream=True)
  File "D:\PROGRAMS\Python\Python35\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "D:\PROGRAMS\Python\Python35\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\PROGRAMS\Python\Python35\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "D:\PROGRAMS\Python\Python35\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=0B7EVK8r0v71pZjFTYXZWM3FlRnM (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000000031BFFD0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))

**Comment by tengshaofeng** [comment]
i also meet the problem, have you fixed it?

**Comment by Lyrichu** [comment]
you might need to go to baidu drive to download the celebA datasets(https://pan.baidu.com/s/1eSNpdRG#list/path=%2FCelebA%2FImg)

**Comment by Dr-Zhou** [comment]
> i also meet the problem, have you fixed it?
maybe because the network problem。

**Comment by WendyMin** [comment]
这是因为网址被墙了，可以从别的地方下载数据集，或者打开vpn再运行语句

**Comment by Neeyan** [comment]
> 这是因为网址被墙了，可以从别的地方下载数据集，或者打开vpn再运行语句

而我是这个问题，我截了个图：
![image](https://user-images.githubusercontent.com/38456964/70619640-67a43e80-1c50-11ea-8bb3-309f892b143a.png)

**Comment by Cauchy-Mars** [comment]
源码下载的网址在这里：https://docs.google.com/ucexport=download&id=0B7EVK8r0v71pZjFTYXZWM3FlRnM，直接下载并放入指定的文件夹即可。

**Comment by AshiakerWang** [comment]
> 源码下载的网址在这里：[https://docs.google.com/ucexport=download&id=0B7EVK8r0v71pZjFTYXZWM3FlRnM，直接下载并放入指定的文件夹即可。](https://docs.google.com/ucexport=download&id=0B7EVK8r0v71pZjFTYXZWM3FlRnM%EF%BC%8C%E7%9B%B4%E6%8E%A5%E4%B8%8B%E8%BD%BD%E5%B9%B6%E6%94%BE%E5%85%A5%E6%8C%87%E5%AE%9A%E7%9A%84%E6%96%87%E4%BB%B6%E5%A4%B9%E5%8D%B3%E5%8F%AF%E3%80%82)

404了，求补链接。
