### ISSUE TITLE
InvalidArgumentError: You must feed a value for placeholder tensor 'real_images' with dtype float and shape

### ISSUE THREAD

**Issue by Proxiaowen** [carpedm20/DCGAN-tensorflow#257]
After i run your code, there are such error news: You must feed a value for placeholder tensor 'real_images' with dtype float and shape.  The 'placegholder' in this error news is the self.input, i define this placeholder as following:

self.inputs=tf.placeholder(tf.float32,[self.batch_size]+image_dims,name='real_images')

In fact, i have feed the placeholder values as follows :
  _, summary_str = self.sess.run([d_optim, self.d_sum],
               feed_dict={ self.inputs: batch_images,
                            self.z: batch_z })
              self.writer.add_summary(summary_str, counter)
        
              # Update G network
              _, summary_str = self.sess.run([g_optim, self.g_sum],
                feed_dict={ self.z: batch_z })
              self.writer.add_summary(summary_str, counter)
        
              # Run g_optim twice to make sure that d_loss does not go to zero (different from paper)
              _, summary_str = self.sess.run([g_optim, self.g_sum],
                feed_dict={ self.z: batch_z })
              self.writer.add_summary(summary_str, counter)
              
              
              
              errD_fake = self.d_loss_fake.eval({ self.z: batch_z })
              errD_real = self.d_loss_real.eval({ self.inputs: batch_images })
              errG = self.g_loss.eval({self.z: batch_z})

Could you can help find the problem? Thanks!

**Comment by P-a-i-s** [comment]
Am facing a similar issue  while running the eval.py script on a test set of data

Here's a snap of the output:

input: ./scripts/eval.sh -net squeezeDet -eval_dir /tmp/bichen/logs/squeezedet -image_set train -gpu 0
output:
No checkpoint file found
Wait 60s for new checkpoints to be saved ... 
Evaluating /tmp/bichen/logs/squeezedet/train/model.ckpt-100...
2018-06-27 08:09:44.938497: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
im_detect: 1/18 im_read: 0.349s detect: 0.829s misc: 0.016s
im_detect: 2/18 im_read: 0.227s detect: 0.749s misc: 0.017s
im_detect: 3/18 im_read: 0.328s detect: 0.729s misc: 0.022s
im_detect: 4/18 im_read: 0.285s detect: 0.717s misc: 0.021s
im_detect: 5/18 im_read: 0.264s detect: 0.706s misc: 0.020s
im_detect: 6/18 im_read: 0.241s detect: 0.688s misc: 0.018s
im_detect: 7/18 im_read: 0.214s detect: 0.685s misc: 0.019s
im_detect: 8/18 im_read: 0.205s detect: 0.672s misc: 0.018s
im_detect: 9/18 im_read: 0.190s detect: 0.662s misc: 0.019s
im_detect: 10/18 im_read: 0.185s detect: 0.651s misc: 0.019s
im_detect: 11/18 im_read: 0.175s detect: 0.644s misc: 0.019s
im_detect: 12/18 im_read: 0.165s detect: 0.644s misc: 0.019s
im_detect: 13/18 im_read: 0.159s detect: 0.635s misc: 0.018s
im_detect: 14/18 im_read: 0.152s detect: 0.634s misc: 0.018s
im_detect: 15/18 im_read: 0.145s detect: 0.633s misc: 0.018s
im_detect: 16/18 im_read: 0.140s detect: 0.633s misc: 0.017s
im_detect: 17/18 im_read: 0.136s detect: 0.627s misc: 0.019s
im_detect: 18/18 im_read: 0.134s detect: 0.630s misc: 0.019s
Evaluating detections...
Running: ./src/dataset/kitti-eval/cpp/evaluate_object ./data/KITTI/training ./data/KITTI/ImageSets/train.txt /tmp/bichen/logs/squeezedet/train/detection_files_100 18
Thank you for participating in our evaluation!
Loading detections...
  done.
Your evaluation results are available in /tmp/bichen/logs/squeezedet/train/detection_files_100
Evaluation summary:
  Average number of detections per image: 8.38888888889:
  Timing:
    im_read: 0.134s detect: 0.630s misc: 0.019s
  Average precisions:
    shades_easy: 0.000
    shades_medium: 0.000
    shades_hard: 0.000
    scarf_easy: 0.000
    scarf_medium: 0.000
    scarf_hard: 0.000
    shoes_easy: 0.000
    shoes_medium: 0.000
    shoes_hard: 0.000
    jacket_easy: 0.000
    jacket_medium: 0.000
    jacket_hard: 0.000
    jeans_easy: 0.000
    jeans_medium: 0.000
    jeans_hard: 0.000
    skull-cap_easy: 0.000
    skull-cap_medium: 0.000
    skull-cap_hard: 0.000
    trousers_easy: 0.000
    trousers_medium: 0.000
    trousers_hard: 0.000
    shirt_easy: 0.000
    shirt_medium: 0.000
    shirt_hard: 0.000
    watch_easy: 0.000
    watch_medium: 0.000
    watch_hard: 0.000
    blazer_easy: 0.000
    blazer_medium: 0.000
    blazer_hard: 0.000
    shades_easy: 0.000
    shades_medium: 0.000
    shades_hard: 0.000
    tshirt_easy: 0.000
    tshirt_medium: 0.000
    tshirt_hard: 0.000
    tie_easy: 0.000
    tie_medium: 0.000
    tie_hard: 0.000
    bag_easy: 0.000
    bag_medium: 0.000
    bag_hard: 0.000
    shorts_easy: 0.000
    shorts_medium: 0.000
    shorts_hard: 0.000
    cardigan_easy: 0.000
    cardigan_medium: 0.000
    cardigan_hard: 0.000
    sweater_easy: 0.000
    sweater_medium: 0.000
    sweater_hard: 0.000
    Mean average precision: 0.000
Analyzing detections...
Detection Analysis:
    Number of detections: 75.0
    Number of objects: 96.0
    Percentage of correct detections: 0.04
    Percentage of localization error: 0.133333333333
    Percentage of classification error: 0.4
    Percentage of background error: 0.413333333333
    Percentage of repeated detections: 0.0133333333333
    Recall: 0.03125
Traceback (most recent call last):
  File "./src/eval.py", line 250, in <module>
    tf.app.run()
  File "/home/ubuntu/sqz_env/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "./src/eval.py", line 246, in main
    evaluate()
  File "./src/eval.py", line 233, in evaluate
    eval_summary_ops, eval_summary_phs, imdb, model)
  File "./src/eval.py", line 132, in eval_once
    eval_summary_str = sess.run(eval_summary_ops, feed_dict=feed_dict)
  File "/home/ubuntu/sqz_env/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/ubuntu/sqz_env/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/sqz_env/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/ubuntu/sqz_env/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_1' with dtype float
	 [[Node: Placeholder_1 = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op u'Placeholder_1', defined at:
  File "./src/eval.py", line 250, in <module>
    tf.app.run()
  File "/home/ubuntu/sqz_env/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "./src/eval.py", line 246, in main
    evaluate()
  File "./src/eval.py", line 181, in evaluate
    ph = tf.placeholder(tf.float32)
  File "/home/ubuntu/sqz_env/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1808, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/ubuntu/sqz_env/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4848, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/ubuntu/sqz_env/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ubuntu/sqz_env/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/ubuntu/sqz_env/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder_1' with dtype float
	 [[Node: Placeholder_1 = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by praveenkumarchandaliya** [comment]
check the place holde value or the size of image with batch[64,64,64,1]
