### ISSUE TITLE
Not able to use a custom dataset

### ISSUE THREAD

**Issue by benckx** [carpedm20/DCGAN-tensorflow#267]
I'm trying to use a custom dataset. I tried with square images as well as with rectangles (with the `--crop` flag). Using `--input_height=60 --output_height=60` doesn't help either.

For example with 60x60 images:
```
$ python main.py --dataset posters_60 --input_height=60 --output_height=60 --train 
{'batch_size': 64,
 'beta1': 0.5,
 'checkpoint_dir': 'checkpoint',
 'crop': False,
 'dataset': 'posters_60',
 'epoch': 25,
 'generate_test_images': 100,
 'input_fname_pattern': '*.jpg',
 'input_height': 60,
 'input_width': None,
 'learning_rate': 0.0002,
 'output_height': 60,
 'output_width': None,
 'sample_dir': 'samples',
 'train': True,
 'train_size': inf,
 'unrolled_lstm': False,
 'visualize': False}
WARNING:tensorflow:From /home/benoit/Tutorials/DCGAN-tensorflow/model.py:106 in build_model.: histogram_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.histogram. Note that tf.summary.histogram uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on their scope.
WARNING:tensorflow:From /home/benoit/Tutorials/DCGAN-tensorflow/model.py:113 in build_model.: histogram_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.histogram. Note that tf.summary.histogram uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on their scope.
WARNING:tensorflow:From /home/benoit/Tutorials/DCGAN-tensorflow/model.py:114 in build_model.: histogram_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.histogram. Note that tf.summary.histogram uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on their scope.
WARNING:tensorflow:From /home/benoit/Tutorials/DCGAN-tensorflow/model.py:115 in build_model.: image_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.image. Note that tf.summary.histogram uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, the max_images argument was renamed to max_outputs.
WARNING:tensorflow:From /home/benoit/Tutorials/DCGAN-tensorflow/model.py:130 in build_model.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /home/benoit/Tutorials/DCGAN-tensorflow/model.py:131 in build_model.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /home/benoit/Tutorials/DCGAN-tensorflow/model.py:135 in build_model.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /home/benoit/Tutorials/DCGAN-tensorflow/model.py:136 in build_model.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
---------
Variables: name (type shape) [size]
---------
generator/g_h0_lin/Matrix:0 (float32_ref 100x8192) [819200, bytes: 3276800]
generator/g_h0_lin/bias:0 (float32_ref 8192) [8192, bytes: 32768]
generator/g_bn0/beta:0 (float32_ref 512) [512, bytes: 2048]
generator/g_bn0/gamma:0 (float32_ref 512) [512, bytes: 2048]
generator/g_h1/w:0 (float32_ref 5x5x256x512) [3276800, bytes: 13107200]
generator/g_h1/biases:0 (float32_ref 256) [256, bytes: 1024]
generator/g_bn1/beta:0 (float32_ref 256) [256, bytes: 1024]
generator/g_bn1/gamma:0 (float32_ref 256) [256, bytes: 1024]
generator/g_h2/w:0 (float32_ref 5x5x128x256) [819200, bytes: 3276800]
generator/g_h2/biases:0 (float32_ref 128) [128, bytes: 512]
generator/g_bn2/beta:0 (float32_ref 128) [128, bytes: 512]
generator/g_bn2/gamma:0 (float32_ref 128) [128, bytes: 512]
generator/g_h3/w:0 (float32_ref 5x5x64x128) [204800, bytes: 819200]
generator/g_h3/biases:0 (float32_ref 64) [64, bytes: 256]
generator/g_bn3/beta:0 (float32_ref 64) [64, bytes: 256]
generator/g_bn3/gamma:0 (float32_ref 64) [64, bytes: 256]
generator/g_h4/w:0 (float32_ref 5x5x3x64) [4800, bytes: 19200]
generator/g_h4/biases:0 (float32_ref 3) [3, bytes: 12]
discriminator/d_h0_conv/w:0 (float32_ref 5x5x3x64) [4800, bytes: 19200]
discriminator/d_h0_conv/biases:0 (float32_ref 64) [64, bytes: 256]
discriminator/d_h1_conv/w:0 (float32_ref 5x5x64x128) [204800, bytes: 819200]
discriminator/d_h1_conv/biases:0 (float32_ref 128) [128, bytes: 512]
discriminator/d_bn1/beta:0 (float32_ref 128) [128, bytes: 512]
discriminator/d_bn1/gamma:0 (float32_ref 128) [128, bytes: 512]
discriminator/d_h2_conv/w:0 (float32_ref 5x5x128x256) [819200, bytes: 3276800]
discriminator/d_h2_conv/biases:0 (float32_ref 256) [256, bytes: 1024]
discriminator/d_bn2/beta:0 (float32_ref 256) [256, bytes: 1024]
discriminator/d_bn2/gamma:0 (float32_ref 256) [256, bytes: 1024]
discriminator/d_h3_conv/w:0 (float32_ref 5x5x256x512) [3276800, bytes: 13107200]
discriminator/d_h3_conv/biases:0 (float32_ref 512) [512, bytes: 2048]
discriminator/d_bn3/beta:0 (float32_ref 512) [512, bytes: 2048]
discriminator/d_bn3/gamma:0 (float32_ref 512) [512, bytes: 2048]
discriminator/d_h4_lin/Matrix:0 (float32_ref 8192x1) [8192, bytes: 32768]
discriminator/d_h4_lin/bias:0 (float32_ref 1) [1, bytes: 4]
Total size of variables: 9451908
Total bytes of variables: 37807632
WARNING:tensorflow:From /home/benoit/Tutorials/DCGAN-tensorflow/model.py:156 in train.: merge_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.merge.
WARNING:tensorflow:From /home/benoit/Tutorials/DCGAN-tensorflow/model.py:158 in train.: merge_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.merge.
WARNING:tensorflow:From /home/benoit/Tutorials/DCGAN-tensorflow/model.py:159 in train.: SummaryWriter.__init__ (from tensorflow.python.training.summary_io) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.FileWriter. The interface and behavior is the same; this is just a rename.
Traceback (most recent call last):
  File "main.py", line 100, in <module>
    tf.app.run()
  File "/home/benoit/tensorflow_DCGAN/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "main.py", line 83, in main
    dcgan.train(FLAGS)
  File "/home/benoit/Tutorials/DCGAN-tensorflow/model.py", line 179, in train
    sample_inputs = np.array(sample).astype(np.float32)
ValueError: could not broadcast input array from shape (60,60,3) into shape (60,60)
```
I'm using the following Virtualenv:
```
$ pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
apt-clone (0.2.1)
apt-xapian-index (0.47)
apturl (0.5.2)
blinker (1.3)
Brlapi (0.6.4)
chardet (2.3.0)
command-not-found (0.3)
cryptography (1.2.3)
defer (1.0.6)
dirspec (13.10)
httplib2 (0.9.1)
idna (2.0)
louis (2.6.4)
lxml (3.5.0)
Mako (1.0.3)
MarkupSafe (0.23)
numpy (1.14.1)
oauthlib (1.0.3)
onboard (1.2.0)
oneconf (0.3.9)
pexpect (4.0.1)
Pillow (3.1.2)
pip (9.0.1)
piston-mini-client (0.7.5)
pkg-resources (0.0.0)
protobuf (3.1.0)
psutil (3.4.2)
ptyprocess (0.5)
pyasn1 (0.1.9)
pycrypto (2.6.1)
pycups (1.9.73)
pycurl (7.43.0)
pygobject (3.20.0)
PyICU (1.9.2)
PyJWT (1.3.0)
python-apt (1.1.0b1)
python-debian (0.1.27)
python-xapp (1.0.0)
pyxdg (0.25)
reportlab (3.3.0)
requests (2.9.1)
scipy (1.0.0)
screen-resolution-extra (0.0.0)
sessioninstaller (0.0.0)
setproctitle (1.1.8)
setuptools (38.5.1)
six (1.10.0)
system-service (0.3)
tensorflow (0.12.0)
thin-client-config-agent (0.8)
ubuntu-drivers-common (0.0.0)
ufw (0.35)
urllib3 (1.13.1)
virtkey (0.63.0)
virtualenv (15.0.1)
wheel (0.30.0)
xkit (0.0.0)
```

**Comment by andreistirb** [comment]
Hello,

I've had the same issue. The problem is because you might have some grayscale images in your dataset. Check out https://github.com/carpedm20/DCGAN-tensorflow/issues/162 for how to find out if you have grayscale images in your dataset, especially jyoo's comment with imagemagick

Hope it helps!

**Comment by benckx** [comment]
Thanks, it seems to be working. I used the following script to convert the greyscale images to RGB:

```bash
for f in $(identify -format "%i %[colorspace]\n" *.jpg | grep -v sRGB | awk '{print $1;}'); do
 convert "$f" -colorspace sRGB -type truecolor "$f"
done
```

**Comment by benckx** [comment]
Duplicate of #162
