### ISSUE TITLE
TypeError: '_FlagValues' object is not iterable

### ISSUE THREAD

**Issue by 2018daofeng** [carpedm20/DCGAN-tensorflow#342]
Traceback (most recent call last):
  File "main.py", line 147, in <module>
    tf.app.run()
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 70, in main
    flags_dict = {k:FLAGS[k].value for k in FLAGS}
TypeError: '_FlagValues' object is not iterable

my input :python main.py --input_height 96 --input_width 96 --output_height 48 --output_width 48 --dataset anime --crop --train --epoch 300 --input_fname_pattern ".jpg"  
so,what's the problem???

**Comment by erjihaoshi** [comment]
Hi  man i wanna  konw if you solve this problem?

**Comment by PonderK** [comment]
@erjihaoshi Hi,i have the same error with you. How to solve? Do you have any suggesstions?

**Comment by erjihaoshi** [comment]
1--input_fname_pattern "*.jpg"
2 in main.py
you can note :    
 # with open(os.path.join(FLAGS.out_dir, 'FLAGS.json'), 'w') as f:
  #   flags_dict = {k:FLAGS[k].value for k in FLAGS._flags}
  #   json.dump(flags_dict, f, indent=4, sort_keys=True, ensure_ascii=False)
then it worked on my comeputer     
good luck for you

**Comment by KryanChen** [comment]
> 1--input_fname_pattern "*.jpg"
> 2 in main.py
> you can note :
> 
> # with open(os.path.join(FLAGS.out_dir, 'FLAGS.json'), 'w') as f:
> # flags_dict = {k:FLAGS[k].value for k in FLAGS._flags}
> # json.dump(flags_dict, f, indent=4, sort_keys=True, ensure_ascii=False)
> then it worked on my comeputer
> good luck for you

still not work for me.

**Comment by KryanChen** [comment]
in main.py
please note:

with open(os.path.join(FLAGS.out_dir, 'FLAGS.json'), 'w') as f:
    flags_dict = {k:flags.FLAGS.__flags[k] for k in flags.FLAGS.__flags}
    json.dump(flags_dict, f, indent=4, sort_keys=True, ensure_ascii=False)


the above changed code worked for me.

**Comment by Yangandtom** [comment]
> in main.py
> please note:
> 
> with open(os.path.join(FLAGS.out_dir, 'FLAGS.json'), 'w') as f:
> flags_dict = {k:flags.FLAGS.__flags[k] for k in flags.FLAGS.__flags}
> json.dump(flags_dict, f, indent=4, sort_keys=True, ensure_ascii=False)
> 
> the above changed code worked for me.

it worked for me

**Comment by chenyida3000** [comment]
Yep, though I didn't notice this issue page, I still solved this problem by **commenting these three lines**.
```
with open(os.path.join(FLAGS.out_dir, 'FLAGS.json'), 'w') as f:
flags_dict = {k:flags.FLAGS.__flags[k] for k in flags.FLAGS.__flags}
json.dump(flags_dict, f, indent=4, sort_keys=True, ensure_ascii=False)
```
Still wanna thank @erjihaoshi for the favor.

**Comment by Jojo696** [comment]
> in main.py
> please note:
> with open(os.path.join(FLAGS.out_dir, 'FLAGS.json'), 'w') as f:
> flags_dict = {k:flags.FLAGS.__flags[k] for k in flags.FLAGS.__flags}
> json.dump(flags_dict, f, indent=4, sort_keys=True, ensure_ascii=False)
> the above changed code worked for me.

It also worked for me. Thanks!!
