### ISSUE TITLE
TypeError: Cannot handle this data type

### ISSUE THREAD

**Issue by mihuzz** [carpedm20/DCGAN-tensorflow#368]
I try to start train on my dataset with image.png image size 250*250
``Traceback (most recent call last):
  File "/home/mihuzz/anaconda3/envs/tf2/lib/python3.7/site-packages/PIL/Image.py", line 2645, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 3), '<f8')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 147, in <module>
    tf.app.run()
  File "/home/mihuzz/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/mihuzz/anaconda3/envs/tf2/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/mihuzz/anaconda3/envs/tf2/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 120, in main
    dcgan.train(FLAGS)
  File "/home/mihuzz/Загрузки/DCGAN-tensorflow-master/model.py", line 195, in train
    grayscale=self.grayscale) for sample_file in sample_files]
  File "/home/mihuzz/Загрузки/DCGAN-tensorflow-master/model.py", line 195, in <listcomp>
    grayscale=self.grayscale) for sample_file in sample_files]
  File "/home/mihuzz/Загрузки/DCGAN-tensorflow-master/utils.py", line 44, in get_image
    resize_height, resize_width, crop)
  File "/home/mihuzz/Загрузки/DCGAN-tensorflow-master/utils.py", line 102, in transform
    resize_height, resize_width)
  File "/home/mihuzz/Загрузки/DCGAN-tensorflow-master/utils.py", line 94, in center_crop
    im = Image.fromarray(x[j:j+crop_h, i:i+crop_w])
  File "/home/mihuzz/anaconda3/envs/tf2/lib/python3.7/site-packages/PIL/Image.py", line 2647, in fromarray
    raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type

**Comment by topxxuki** [comment]
same question like you

**Comment by topxxuki** [comment]
> same question like you
 i solved my problem by following this issue:
https://github.com/carpedm20/DCGAN-tensorflow/issues/366

it may help u

**Comment by yuuyuuko** [comment]
me too.
