### ISSUE TITLE
checkpoint not found

### ISSUE THREAD

**Issue by QAutumn** [carpedm20/DCGAN-tensorflow#380]
Does anyone know how to solve this problem？
Total size of variables: 21985668 Total bytes of variables: 87942672  [*] Reading checkpoints... ./out/20200424.235443 - data - ag/checkpoint  [*] Failed to find a checkpoint Traceback (most recent call last):   File "main.py", line 147, in <module>     tf.app.run()   File "/Users/qiu/Library/Python/2.7/lib/python/site-packages/tensorflow/python/platform/app.py", line 40, in run     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)   File "/Users/qiu/Library/Python/2.7/lib/python/site-packages/absl/app.py", line 299, in run     _run_main(main, args)   File "/Users/qiu/Library/Python/2.7/lib/python/site-packages/absl/app.py", line 250, in _run_main     sys.exit(main(argv))   File "main.py", line 124, in main     raise Exception("Checkpoint not found in " + FLAGS.checkpoint_dir) Exception: Checkpoint not found in ./out/20200424.235443 - data - ag/checkpoint

**Comment by KoreanJ** [comment]
Having the same issue here. Used my own data set of 64x64 RGB images (roughly 200 in batch size) and it seems none of my checkpoint directories have anything saved in them

**Comment by KoreanJ** [comment]
This seems to have been fixed in @336 

Checkpoints are saved by default every 200 epochs so anything less won't get saved. You need to use `--ckpt_freq` to change that
