### ISSUE TITLE
'module' object has no attribute 'imread'

### ISSUE THREAD

**Issue by c1a1o1** [carpedm20/DCGAN-tensorflow#52]
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "main.py", line 44, in main
    dcgan.train(FLAGS)
  File "/home/caocao/DCGAN-tensorflow/model.py", line 150, in train
    sample = [get_image(sample_file, self.image_size, is_crop=self.is_crop, resize_w=self.output_size, is_grayscale = self.is_grayscale) for sample_file in sample_files]
  File "/home/caocao/DCGAN-tensorflow/model.py", line 150, in <listcomp>
    sample = [get_image(sample_file, self.image_size, is_crop=self.is_crop, resize_w=self.output_size, is_grayscale = self.is_grayscale) for sample_file in sample_files]
  File "/home/caocao/DCGAN-tensorflow/utils.py", line 18, in get_image
    return transform(scipy.misc.imread(image_path, is_grayscale), image_size, is_crop, resize_w)

**Comment by carpedm20** [comment]
See http://stackoverflow.com/questions/15345790/scipy-misc-module-has-no-attribute-imread.

**Comment by c1a1o1** [comment]
@carpedm20   Thank you  ! Do you  have a email
