### ISSUE TITLE
attribute error while loading model for test

### ISSUE THREAD

**Issue by Exception4U** [carpedm20/DCGAN-tensorflow#54]
python main.py --dataset mnist --visualize True
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

 [*] Reading checkpoints...
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "main.py", line 49, in main
    to_json("./web/js/layers.js", [dcgan.h0_w, dcgan.h0_b, dcgan.g_bn0],
AttributeError: 'DCGAN' object has no attribute 'h0_w'

**Comment by raniamlj** [comment]
hi
i have the same problem, 
any solution please!

**Comment by carpedm20** [comment]
`--visualize` is not for visualization. If you want to train, you need to use:

    python main.py --dataset mnist --is_train True

If you want to test, use:

    python main.py --dataset mnist --is_train False

Don't touch `--visualize` and always use `--visualize=False`

**Comment by raniamlj** [comment]
Thank your for your reply 
unfortunately, when we comment to_josn method we get those errors: 
------------------------------------------
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    tf.app.run()
  File "/home/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "main.py", line 57, in main
    visualize(sess, dcgan, FLAGS, OPTION)
  File "/home/DCGAN-tensorflow-master/utils.py", line 171, in visualize
    samples = sess.run(dcgan.sampler, feed_dict={dcgan.z: z_sample})
  File "/home/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 710, in run
    run_metadata_ptr)
  File "/home/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 908, in _run
    feed_dict_string, options, run_metadata)
  File "/home/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 958, in _do_run
    target_list, options, run_metadata)
  File "/home/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 978, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: You must feed a value for placeholder tensor 'y' with dtype float and shape [64,65]
	 [[Node: y = Placeholder[dtype=DT_FLOAT, shape=[64,65], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Caused by op u'y', defined at:
  File "main.py", line 60, in <module>
    tf.app.run()
  File "/home/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "main.py", line 38, in main
    dataset_name=FLAGS.dataset, is_crop=FLAGS.is_crop, checkpoint_dir=FLAGS.checkpoint_dir)
  File "/home/DCGAN-tensorflow-master/model.py", line 68, in __init__
    self.build_model()
  File "/home/DCGAN-tensorflow-master/model.py", line 72, in build_model
    self.y= tf.placeholder(tf.float32, [self.batch_size, self.y_dim], name='y')
  File "/home/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1212, in placeholder
    name=name)
  File "/home/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1530, in _placeholder
    name=name)
  File "/home/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/home/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2317, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1239, in __init__
    self._traceback = _extract_stack()
---------------------------------------

and when we test with only: 
python main.py --dataset mnist --is_train False
nothing appear as result
