### ISSUE TITLE
own dataset:  Shapes (64, 4, 4, 256) and (64, 3, 3, 256) are not compatible

### ISSUE THREAD

**Issue by JohannesHeidecke** [carpedm20/DCGAN-tensorflow#79]
Hi there,

When using my own dataset (28x28, grayscale), I get an error for this line in `model.py`:

`g_optim = tf.train.AdamOptimizer(config.learning_rate, beta1=config.beta1) \`
     `.minimize(self.g_loss, var_list=self.g_vars)`

error:
`Traceback (most recent call last):
  File "...tensorflow/python/framework/tensor_shape.py", line 575, in merge_with
    new_dims.append(dim.merge_with(other[i]))`
  `File "...tensorflow/python/framework/tensor_shape.py", line 133, in merge_with
    self.assert_is_compatible_with(other)`
  `File "...tensorflow/python/framework/tensor_shape.py", line 108, in assert_is_compatible_with
    % (self, other))`
`ValueError: Dimensions 4 and 3 are not compatible`
`During handling of the above exception, another exception occurred:`
`Traceback (most recent call last):`
 ` File "main.py", line 74, in <module>`
  `  tf.app.run()`
  `File "...tensorflow/python/platform/app.py", line 30, in run`
   ` sys.exit(main(sys.argv[:1] + flags_passthrough))`
 ` File "main.py", line 59, in main`
   ` dcgan.train(FLAGS)`
  `File "...DCGAN-tensorflow/model.py", line 139, in train`
    `.minimize(self.g_loss, var_list=self.g_vars)`
 ` File "...tensorflow/python/training/optimizer.py", line 196, in minimize`
   ` grad_loss=grad_loss)`
  `File "...tensorflow/python/training/optimizer.py", line 253, in compute_gradients`
    `colocate_gradients_with_ops=colocate_gradients_with_ops)`
  `File "...tensorflow/python/ops/gradients.py", line 491, in gradients`
    `in_grad.set_shape(t_in.get_shape())`
  `File "...tensorflow/python/framework/ops.py", line 408, in set_shape`
    `self._shape = self._shape.merge_with(shape)`
  `File "...tensorflow/python/framework/tensor_shape.py", line 579, in merge_with`
    `(self, other))`
`ValueError: Shapes (64, 4, 4, 256) and (64, 3, 3, 256) are not compatible`

Any advice on how to fix this?

**Comment by carpedm20** [comment]
Hmm.. I'm not sure but the fast simple bypass might be adding [tf.image.resize_images](https://www.tensorflow.org/api_docs/python/image/resizing#resize_images) right after 

    self.images = tf.placeholder(tf.float32, 
                                [self.batch_size] + [self.output_size, self.output_size, self.c_dim],
                                name='real_images')

is defined.

**Comment by JohannesHeidecke** [comment]
Ah can you specify what exactly I need to resize? My images are png format, 28x28x1. 

I replaced jpg with png in 
`data = glob(os.path.join("./data", config.dataset, "*.jpg"))`

and I am passing `image_size=28` and `c_dim=1`.

**Comment by carpedm20** [comment]
I tried my best to fix the code to avoid the error occurred by using a custom dataset. Please try again and remove checkpoints before you run the code.

**Comment by hercky** [comment]
Hi

The issue is because of how you are creating the Generator network ( the divide by 16 operation I think is messing things up here ). A quick workaround can be to use use the generator with two hidden layers (/2 and /4), as in the mnist example. I was able to run not mnist by replacing the generator method with this:

```
    def generator(self, z, y=None):
        with tf.variable_scope("generator") as scope:

            s = self.output_size
            s_2, s_4 = int(s/2), int(s/4)

            h0 = tf.nn.relu(
                self.g_bn0(linear(z, self.gfc_dim, 'g_h0_lin')))
            
            h1 = tf.nn.relu(self.g_bn1(
                linear(h0, self.gf_dim*2*s_4*s_4, 'g_h1_lin')))
            h1 = tf.reshape(h1, [self.batch_size, s_4, s_4, self.gf_dim * 2])

            h2 = tf.nn.relu(self.g_bn2(deconv2d(h1,
                [self.batch_size, s_2, s_2, self.gf_dim * 2], name='g_h2')))
            
            return tf.nn.sigmoid( deconv2d(h2, [self.batch_size, s, s, self.c_dim], name='g_h3'))
```

I'm not sure if this is the correct way of doing things here, maybe @carpedm20  can shed some light on it.

**Comment by carpedm20** [comment]
@hercky Oh I see. The problem was the size of input is too small for 4 layer networks and it's not dividable. I think it's tricky problem that a depth of network highly depends on input width, height and there is no one answer for it. I'll just add a `raise Exception` code if the input size is "too small" for the current network design and suggest people to change it.

**Comment by ianni67** [comment]
I'm trying to understand how to fix the issue in my case (I don't assume I can fix it for the general case, but, who knows?). In my ignorance, I don't understand the meaning of the y_dim parameter. 
Any kind soul who can provide a short explanation?
