### ISSUE TITLE
AttributeError: 'module' object has no attribute 'imsave'

### ISSUE THREAD

**Issue by TRGNN** [carpedm20/DCGAN-tensorflow#81]
Hello !

I followed the instruction for training with celebA dataset and I get this error

```
Traceback (most recent call last):
  File "main.py", line 74, in <module>
    tf.app.run()
  File "/home/workshop/miniconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "main.py", line 59, in main
    dcgan.train(FLAGS)
  File "/media/workshop/DocumentsC1/Learning/DCGAN-tensorflow/model.py", line 236, in train
    './{}/train_{:02d}_{:04d}.png'.format(config.sample_dir, epoch, idx))
  File "/media/workshop/DocumentsC1/Learning/DCGAN-tensorflow/utils.py", line 21, in save_images
    return imsave(inverse_transform(images), size, image_path)
  File "/media/workshop/DocumentsC1/Learning/DCGAN-tensorflow/utils.py", line 43, in imsave
    return scipy.misc.imsave(path, merge(images, size))
AttributeError: 'module' object has no attribute 'imsave'
```

Any idea ?

**Comment by ppwwyyxx** [comment]
You need to install pillow.

**Comment by TRGNN** [comment]
Ok, it was obvious. The issue was the guy on the computer.

Thanks !
