### ISSUE TITLE
python main.py --dataset mnist --input_height=28 --input_width=28 --c_dim=1 --is_train   got following error?

### ISSUE THREAD

**Issue by eecrazy** [carpedm20/DCGAN-tensorflow#82]
[*] Reading checkpoints...
 [*] Failed to find a checkpoint
 [!] Load failed...
Traceback (most recent call last):
  File "main.py", line 91, in <module>
    tf.app.run()
  File "/users1/zyli/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "main.py", line 74, in main
    dcgan.train(FLAGS)
  File "/users3/zyli/project/github/DCGAN-tensorflow/model.py", line 222, in train
    self.y:batch_labels,
  File "/users1/zyli/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/users1/zyli/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 943, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (64, 28, 28, 1) for Tensor u'real_images:0', which has shape '(64, 64, 64, 1)'

**Comment by eecrazy** [comment]
python main.py --dataset mnist --input_height=28 --input_width=28 --output_height=28 --output_width=28  --c_dim=1 --is_train
set  --output_height=28 --output_width=28  solve this problem.   I find image_dims in model.py use these two variables, but default value is 64.

**Comment by carpedm20** [comment]
@eecrazy Yes, sorry for my mistake. I changed the commands where can omit `_width` if `_height is specified` so now you can run `mnist` with:

    python main.py --dataset mnist --input_height=28 --output_height=28 --c_dim=1 --is_train
