### ISSUE TITLE
AttributeError: 'module' object has no attribute 'concat_v2'

### ISSUE THREAD

**Issue by shivajid** [carpedm20/DCGAN-tensorflow#94]
I am getting the following error on running
Command
"python main.py --dataset mnist --input_height=28 --output_height=28 --c_dim=1 --is_train"
Error
Traceback (most recent call last):
  File "main.py", line 96, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "main.py", line 62, in main
    sample_dir=FLAGS.sample_dir)
  File "/media/sdutta/A2785C9D785C7251/DCGAN-tensorflow/model.py", line 71, in __init__
    self.build_model()
  File "/media/sdutta/A2785C9D785C7251/DCGAN-tensorflow/model.py", line 95, in build_model
    self.G = self.generator(self.z, self.y)
  File "/media/sdutta/A2785C9D785C7251/DCGAN-tensorflow/model.py", line 383, in generator
    z = tf.concat_v2([z, y], 1)
AttributeError: 'module' object has no attribute 'concat_v2'

Any thoughts?

**Comment by carpedm20** [comment]
You're tensorflow version is lower than 0.12.0 which doesn't have `concat_v2`.

**Comment by bazinac** [comment]
It seems to be removed in 1.0... Is there something with same functionality in 1.0?

**Comment by ppwwyyxx** [comment]
@bazinac `tf.concat`.

**Comment by bazinac** [comment]
Oh I see, thanks
